# Generated by Django 4.1.3 on 2022-11-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, default=None, null=True)),
                ('nombre', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('estado', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('telefono', models.BigIntegerField(default=None, null=True)),
                ('direccion', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('fecha_entrega', models.DateField(blank=True, default=None, null=True)),
                ('franja_hora', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('conductor', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
